name: Pull docker image
description: Pull docker image

inputs:
  image:
    description: The docker image to pull
    required: true
    default: kmake-image:latest

runs:
  using: "composite"
  steps:
    - name: Clone kmake-image
      shell: bash
      run: |
        git clone https://github.com/qualcomm-linux/kmake-image.git

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: false
        tags: kmake-image:latest
        context: kmake-image
        cache-from: type=gha
        cache-to: type=gha,mode=max
