name: Build docker image
description: Build docker image

inputs:
  image_tag:
    description: The tag to apply to the built docker image
    required: true
    default: kmake-image:latest
  image_context:
    description: The context to use for the image build. Likely a git repo URL.
    required: true
    default: https://github.com/qualcomm-linux/kmake-image.git

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: false
        load: true
        tags: ${{ inputs.image_tag }}
        context: ${{ inputs.image_context }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
