name: _build
on:
  workflow_call:
    inputs:
      docker_image:
        description: Docker image
        type: string
        required: true

jobs:
  build:
    runs-on:
      group: GHA-Kernel-SelfHosted-RG
      labels: [ self-hosted, kernel-prd-u2404-x64-large-od-ephem ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync codebase
        id: sync
        uses: qualcomm-linux/kernel-config/.github/actions/sync@main
        with:
          base_branch: ${{ github.base_ref }}
          pr_number: ${{ github.event.pull_request.number }}

      - name: Build docker image
        uses: qualcomm-linux/kernel-config/.github/actions/build_docker_image@main
        with:
          image_tag: ${{ inputs.docker_image }}

      - name: Build workspace
        id: build_workspace
        uses: qualcomm-linux/kernel-config/.github/actions/build@main
        with:
          docker_image: ${{ inputs.docker_image }}
          workspace_path: ${{ steps.sync.outputs.workspace_path }}

      - name: Create file list for artifacts upload
        run: |
          cd ${{ steps.sync.outputs.workspace_path }}
          touch ${{ github.workspace }}/artifacts/file_list.txt
          tar -cJf ${{ github.workspace }}/modules.tar.xz ../kobj/tar-install/lib/modules/
          echo "${{ github.workspace }}/modules.tar.xz" >> ${{ github.workspace }}/artifacts/file_list.txt
          echo "${{ steps.sync.outputs.workspace_path }}/../kobj/arch/arm64/boot/Image" >> ${{ github.workspace }}/artifacts/file_list.txt
          echo "${{ steps.sync.outputs.workspace_path }}/../kobj/vmlinux" >> ${{ github.workspace }}/artifacts/file_list.txt
          echo "${{ steps.sync.outputs.workspace_path }}/../kobj/arch/arm64/boot/dts/qcom/qcs6490-rb3gen2.dtb" >> ${{ github.workspace }}/artifacts/file_list.txt

      - name: Upload artifacts
        uses: qualcomm-linux/kernel-config/.github/actions/aws_s3_helper@main
        with:
          s3_bucket: qli-prd-kernel-gh-artifacts
          local_file: ${{ github.workspace }}/artifacts/file_list.txt
          mode: multi-upload

      - name: Clean up
        run: |
          rm -rf artifacts
          rm -rf kobj
          rm -rf modules.tar.xz

      - name: Update summary
        if: success() || failure()
        shell: bash
        run: |
          if [ ${{ steps.build_workspace.outcome }} == 'success' ]; then
            echo "Build was successful"
            summary=":heavy_check_mark: Build Success"
          else
            echo "Build failed"
            summary=":x: Build Failed"
          fi
          SUMMARY='
          <details><summary><i>Build Summary</i></summary>
          '${summary}'
          </details>
          '
          echo -e "$SUMMARY" >> $GITHUB_STEP_SUMMARY
