name: PR email addresses checker

on:
  workflow_dispatch:
    inputs:
      pr:
        description: pull request
        type: string
        required: true
      sha:
        description: sha
        type: string
        required: true
      ref:
        description: ref
        type: string
        required: true
      repo:
        description: repo
        type: string
        required: true

permissions:
  pull-requests: read
jobs:
  init-status:
    runs-on: ubuntu-latest
    steps:
      - name: Initial workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@coral
        with:
          sha: ${{ inputs.sha }}
          action_mode: start
          check_name: email-checker
          repo: ${{ inputs.repo }}

  pr-check-emails:
    runs-on: ubuntu-latest
    steps:      
      - name: Check PR emails
        uses: qualcomm/commit-emails-check-action@coral

  final-status:
    runs-on: ubuntu-latest
    needs: [pr-check-emails]
    if: always()
    steps:
      - name: Final workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@coral
        with:
          sha: ${{ github.sha }}
          action_mode: ${{ needs.pr-check-emails.result }}
          check_name: email-checker
          repo: ${{ inputs.repo }}
