name: PR email addresses checker topics

on:
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request number
        type: string
        required: true
      sha:
        description: Head sha of the PR
        type: string
        required: true
      ref:
        description: Target branch
        type: string
        required: true
      repo:
        description: Target repository
        type: string
        required: true

permissions:
  pull-requests: read
jobs:
  init-status:
    runs-on: ubuntu-latest
    steps:
      - name: Initial workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: start
          check_name: email-checker
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}

  pr-check-emails:
    runs-on: ubuntu-latest
    steps:      
      - name: Check PR emails
        uses: qualcomm/commit-emails-check-action@main

  final-status:
    runs-on: ubuntu-latest
    needs: [pr-check-emails]
    if: always()
    steps:
      - name: Final workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ github.sha }}
          action_mode: ${{ needs.pr-check-emails.result }}
          check_name: email-checker
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}
