name: Kernel Checkers
on:
  workflow_dispatch:
    inputs:
      pr:
        description: Pull request number
        type: string
        required: true
      sha:
        description: Head sha of the PR
        type: string
        required: true
      ref:
        description: Target branch
        type: string
        required: true
      repo:
        description: Target repository
        type: string
        required: true

jobs:
  init-status:
    runs-on: ubuntu-latest
    steps:
      - name: Initial workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: start
          check_name: kernel-checker
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}

  checker:
    needs: [init-status]
    uses: qualcomm-linux/kernel-checkers/.github/workflows/checker.yml@main
    with:
      check_name: ${{ matrix.check }}
      base_branch: ${{ inputs.ref }}
      pr_number: ${{ inputs.pr }}
      topic_repo: ${{ inputs.repo }}
    strategy:
      matrix:
        check: [check-patch-compliance, check-uapi-headers, sparse-check, checkpatch,
          dt-binding-check, dtb-check]
      fail-fast: false
  
  final-status:
    runs-on: ubuntu-latest
    needs: [checker]
    if: always()
    steps:
      - name: Final workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@main
        with:
          sha: ${{ inputs.sha }}
          action_mode: ${{ needs.checker.result }}
          check_name: kernel-checker
          repo: ${{ inputs.repo }}
          GH_TOKEN: ${{ secrets.PAT }}
