name: pre_merge_topics
on:
  workflow_dispatch:
    inputs:
      pr:
        description: pr
        type: string
        required: true
      sha:
        description: sha
        type: string
        required: true
      ref:
        description: ref
        type: string
        required: true
      repo:
        description: repo
        type: string
        required: true
jobs:
  init-status:
    runs-on: ubuntu-latest
    steps:
      - name: Initial workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@coral
        with:
          sha: ${{ inputs.sha }}
          action_mode: start
          check_name: pre-merge
          repo: ${{ inputs.repo }}

  pre-merge:
    needs: [init-status]
    uses: qualcomm-linux/kernel-config/.github/workflows/pre_merge.yml
    secrets: inherit
    with:
      pr_number: ${{ inputs.pr }}
      branch: ${{ inputs.ref }}

  final-status:
    runs-on: ubuntu-latest
    needs: [pre-merge]
    if: always()
    steps:
      - name: Final workflow status
        uses: qualcomm-linux/kernel-config/.github/actions/workflow_status@coral
        with:
          sha: ${{ github.sha }}
          action_mode: ${{ needs.pr-check-emails.result }}
          check_name: email-checker
          repo: ${{ inputs.repo }}
