name: pre_merge
on:
  workflow_call:
    inputs:
      pr:
        required: false
        type: string
      branch:
        required: false
        type: string

jobs:
  loading:
    uses: ./.github/workflows/loading.yml
    secrets: inherit

  build:
    needs: loading
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      pr_number: ${{ inputs.pr }}
      branch: ${{ inputs.branch }}

  test:
    needs: [loading, build]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      docker_image: kmake-image:ver.1.0
      build_matrix: ${{ needs.loading.outputs.build_matrix }}
      full_matrix: ${{ needs.loading.outputs.full_matrix }}
